config/routes.rb
Rails.application.routes.draw do
  get 'helpful/index'
  get 'locations/posts'
  get 'locations/index'
  resources :locations
  
  devise_for :users
  root to: "home#index"
  
  resources :users, :only => [:posts]
  resources :locations, :only => [:new] do
    resources :reviews, only: [:index, :create]
  end  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/location.rb
class Location < ApplicationRecord
  mount_uploader :location_image, ImageUploader
  has_one_attached :location_image
  
  geocoded_by :address
  after_validation :geocode, if: :address_changed?
  
  belongs_to :user, optional: true
  has_many :reviews, dependent: :destroy
  
  def avg_score
    unless self.reviews.empty?
      reviews.average(:score).round(1).to_f
    else
      0.0
    end
  end
  def review_score_percentage
    unless self.reviews.empty?
      reviews.average(:score).round(1).to_f*100/5
    else
      0.0
    end
  end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :location
  validates :score, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :locations, dependent: :destroy
  has_many :reviews, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  def set_search
    @users = User.all
    @locations = Location.all
    @q = Location.ransack(params[:q])
    @locations = @q.result(distinct: true)
  end
  
  private
  
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end
end

app/controllers/helpful_controller.rb
class HelpfulController < ApplicationController
  def Drives
  end

  def index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @q = Location.ransack(params[:q])
    @locations = @q.result(distinct: true)
  end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  
  def index
    @locations = Location.all
    @q = Location.ransack(params[:q])
    @locations = @q.result(distinct: true)
  end
  
  def new
    @location = Location.new
  end
  
  def create
    @location = Location.new(location_params)
    @location.user_id = current_user.id
    @location.save
    redirect_to locations_posts_path
  end
  
  def posts
    @locations = current_user.locations.all
  end
  
  def show
    @location = Location.find(params[:id])
    @review = Review.new
  end
  
  def destroy
    @location = Location.find(params[:id])
    if @location.user != current_user
      redirect_to locations_posts_path
    else
      @location.destroy
      redirect_to locations_posts_path
    end
  end
  
  def edit
    @location = Location.find(params[:id])
  end

  def update
    @location = Location.find(params[:id])
    if @location.update(params.require(:location).permit(:location_name,:introduction,:address,:price,:location_image))
      redirect_to locations_posts_path
    else
      render "edit"
    end
  end
  
  private
    def location_params
      params.require(:location).permit(:location_name,:introduction,:address,:price,:location_image)
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
before_action :authenticate_user!, only: [:create]
  def index
    @location = Location.find(params[:location_id])
    @reviews = @location.reviews
  end
  
  def create
    @review = Review.new(review_params)
    @review.user_id = current_user.id
    if @review.save
      redirect_to location_reviews_path(@review.location)
    else
      @location = Location.find(params[:location_id])
      render "locations/show"
    end
  end
  
  private
  def review_params
    params.require(:review).permit(:location_id, :score, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/helpful_helper.rb
module HelpfulHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/helpful/index.html.erb
<section class="main-section">
  <div class="container1">
    <h1 class="title3">「今日どうする？」<br>解決します。</h1>
  </div>
</section>
<section class="main-section">
  <div class="contents-width">
    <header class="section-header contents-tidy bottom-line">
      <h2 class="titel">
        <span>どんなサービス？</span>
      </h2>
      <p>What services?</p>
    </header>
    <div class="main-text">
      <div class="sub-text">
        <p>皆さんはこんな会話一度は経験したことありませんか？<br>「Aさん:今日どこ行く？」<br>「Bさん:どこでいいよ〜」<br>私はこのような会話は数え切れない程してきました。そんな問題を解決するのがこのサービスです！</p>
      </div>
      <h2 class="titel2">
        <span>使い方</span>
      </h2>
      <div class="sub-text">
        <p>トップページにある検索欄から「県名(埼玉県・さいたまけん)」で調べます。<br>調べた県のドライブスポットなどが出てきます。<br>更に新規登録し、ログインすると検索だけではなく、行ってみて良かったところの場所を登録できます！
        <br>皆さんで、いい場所・穴場スポット・ドライブスポットを共有していきましょう！</p>
      </div>
      <div class="ikou_btn">
        <a href="/" class="btn btn-border"><span>今すぐ検索してみる！</span></a>
      </div>
    </div>
  </div>
</section>

app/views/home/index.html.erb
<div class="top">
  <div class="top-main">
    <div class="row col-lg-6">
      <div class="form-fream">
        <div class="form-area">
          <p class="form-area-title">旅に出よう。</p>
          <%= search_form_for @q  do |f| %>
            <%= f.search_field :address_cont,placeholder: '例）埼玉県春日部市' %>
            <%= f.submit "検索", class: "button1"%>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Portfolio2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.9.0/css/all.min.css" integrity="sha256-UzFD2WYH2U1dQpKDjjZK72VtPeWP50NoJjd26rnAdUI=" crossorigin="anonymous" />
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/a2ed1e393c.js" crossorigin="anonymous"></script>
  </head>

  <body>
    <% if flash[:notice] %>
      <div class="notification is-info">
        <p class="notice"><%= notice %></p>
      </div>
    <% end %>
    
    <% if flash[:alert] %>
      <div class="notification is-danger">
        <p class="alert"><%= alert %></p>
      </div>
    <% end %>
    
    <% if user_signed_in? %>
    <header class="page-header" id="header">
      <div class="navbar-item">
        <a href="/" class="title is-4" style="font-family: cursive;">Asobuno Tanosiiina</a>
        <p class="control">
          <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "button logout" %>
        </p>
      </div>
      <div id="navbarExampleTransparentExample" class="navbar-menu">
        <div class="navbar-end1">
          <div class="navbar-item">
            <div class="field is-grouped">
              <p class="control">
                <%= link_to "TOP", root_path, class: "button is-warning is-light" %>
              </p>
              <p class="control">
                <%= link_to "Asobuno Tanosiiinaとは?", helpful_index_path, class: "button is-warning is-light" %>
              </p>
              <p class="control">
                <%= link_to "スポット登録", new_location_path, class: "button is-warning is-light" %>
              </p>
              <p class="control">
                <%= link_to "スポット登録一覧", locations_posts_path, class: "button is-warning is-light" %>
              </p>
            </div>
          </div>
        </div>
      </div>
    <% else %>
      <div class="navbar-item">
        <a href="/" class="title is-4" style="font-family: cursive;">Asobuno Tanosiiina</a>
      </div>
      <div id="navbarExampleTransparentExample" class="navbar-menu">
        <div class="navbar-end2">
          <div class="navbar-item">
            <div class="field is-grouped">
              <p class="control">
                <%= link_to "TOP", root_path, class: "button is-warning is-light2" %>
              </p>
              <p class="control">
                <%= link_to "Asobuno Tanosiiinaとは?", helpful_index_path, class: "button is-warning is-light2" %>
              </p>
              <p class="control">
                <%= link_to "ログイン", new_user_session_path, class: "button is-warning is-light2" %>
              </p>
              <p class="control">
                <%= link_to "新規登録", new_user_registration_path, class: "button is-warning is-light2" %>
              </p>
            </div>
          </div>
        </div>
      </div>
    <% end %>
    <%= yield %>
    <footer id="footer01" class="footer outer-block">
      <div class="logo">
        <a href="/" class="title is-5" style="font-family: cursive;">Asobuno Tanosiiina</a>
      </div>
      <p class="copyright">
        © 2021 Copyright: Asobuno Tanosiiina
      </p>
    </footer>
  </body>
</html>

app/views/locations/edit.html.erb
<div class="edit-main">
  <div class="cont_title1">
    <h1>スポット編集</h1><hr>
  </div>
  <%= form_with model: @location, local: true  do |f| %>
    <table class="location_info_base4">
      <thead>
        <tr class="arrow_box">
          <th><%= f.label :location_name,'スポット名' %></th>
          <td><%= f.text_field :location_name, placeholder: 'スポット名を入力' %></td>
        </tr>
        <tr class="arrow_box">
          <th><%= f.label :introduction,'スポット紹介' %></th>
          <td><%= f.text_area :introduction, placeholder: '例）越谷レイクタウンは埼玉県越谷市にある大型ショッピングモールです！中には映画館などもあるのでおすすめです！' %></td>
        </tr>
        <tr class="arrow_box">
          <th><%= f.label :address,'住所を入力' %></th>
          <td><%= f.text_field :address, placeholder: '住所を入力' %></td>
        </tr>
        <tr class="arrow_box">
          <th><%= f.label :price,'予算を入力' %></th>
          <td><%= f.number_field :price, placeholder: '予算を入力' %></td>
        </tr>
      </thead>
    </table>
    <div class="done_button">
      <ul>
        <li><%= f.submit "スポット編集を完了する" %></li>
        <li><%= link_to "登録済みスポット一覧に戻る", locations_posts_path %></li>
      </ul>
    </div>
  <% end %>
</div>

app/views/locations/index.html.erb
<div class="index-main">
  <div class="cont_title2">
    <h1>みんなのスポット一覧</h1><hr>
  </div>
  <table class="location_info_base2">
    <thead>
      <% @locations.each do |location| %>
        <tr class="arrow_box">
          <th>登録番号</th>
          <td><%= location.id %></td>
        </tr>
        <tr class="arrow_box">
          <th>スポット名</th>
          <td><%= location.location_name %></td>
        </tr>
        <tr class="arrow_box">
          <th>料金・予算</th>
          <td><%= location.price %>円</td>
        </tr>
        <tr class="arrow_box">
          <th>どんな所？</th>
          <td><%= location.introduction %></td>
        </tr>
        <tr class="arrow_box">
          <th>住所</th>
          <td><%= location.address %></td>
        </tr>
        <tr class="arrow_box">
          <th>詳細</th>
          <td><%= link_to "詳細を見る", location %></td>
        </tr>
        <tr class="touroku">
          <th>消去</th>
          <% if location.user == current_user %>
            <td><%= link_to "消去しますか？", location, method: :delete, data: { confirm: "本当に削除しますか？" } %></td>
          <% else %>
        　   <td></td>
          <% end %>
        </tr>
      <% end %>
    </thead>
  </table>
</div>
 

app/views/locations/new.html.erb
<div class="new-main">
  <div class="cont_title5">
    <h1>スポット情報登録</h1><hr>
  </div>
  <%= form_with model: @location, local: true  do |f| %>
    <table class="location_info_base5">
      <thead>
        <tr class="arrow_box">
          <th><%= f.label :location_name,'スポット名' %></th>
          <td><%= f.text_field :location_name, placeholder: 'スポット名を入力' %></td>
        </tr>
        <tr class="arrow_box">
          <th><%= f.label :introduction,'スポット紹介' %></th>
          <td><%= f.text_area :introduction, placeholder: 'スポット紹介を入力' %></td>
        </tr>
        <tr class="arrow_box">
          <th><%= f.label :address,'住所を入力' %></th>
          <td><%= f.text_field :address, placeholder: '住所を入力' %></td>
        </tr>
        <tr class="arrow_box">
          <th><%= f.label :price,'料金・予算を入力' %></th>
          <td><%= f.number_field :price, placeholder: '予算を入力' %></td>
        </tr>
      </thead>
    </table>
    <div class="done_button">
      <%= f.submit '登録完了する' %>
    </div>
  <% end %>
</div>

app/views/locations/posts.html.erb
<div class="post-main">
  <div class="cont_title">
    <h1>登録済みスポット一覧（自分で登録）</h1><hr>
  </div>
  <table class="location_info_base1">
    <thead>
      <% @locations.each do |location| %>
        <tr class="arrow_box">
          <th>スポット名</th>
          <td><%= location.location_name %></td>
        </tr>
        <tr class="arrow_box">
          <th>料金・予算</th>
          <td><%= location.price %>円</td>
        </tr>
        <tr class="arrow_box">
          <th>どんな所？</th>
          <td><%= location.introduction %></td>
        </tr>
        <tr class="arrow_box">
          <th>住所</th>
          <td><%= location.address %></td>
        </tr>
        <tr class="touroku">
          <th>詳細・編集・削除</th>
          <td><%= link_to "詳細を見る", location %><br><%= link_to "編集", edit_location_path(location) %><br><%= link_to "削除しますか？", location, method: :delete, data: { confirm: "本当に削除しますか？" } %> <br>
        </tr>
      <% end %>
    </thead>
  </table>
</div>
 

app/views/locations/show.html.erb
<div class="show-main">
  <div class="cont_title3">
    <h1>スポット詳細ページ</h1><hr>
  </div>
  <table class="location_info_base3">
    <thead>
      <tr class="arrow_box">
        <th>スポット名</th>
        <td><%= @location.location_name %></td>
      </tr>
      <tr class="arrow_box">
        <th>料金・予算</th>
        <td><%= @location.price %>円</td>
      </tr>
      <tr class="arrow_box">
        <th>住所</th>
        <td><%= @location.address %><div id="map"></div></td>
        <script type="text/javascript">
          function initMap() {var test ={lat: <%= @location.latitude %>, lng: <%= @location.longitude %>};
            var map = new google.maps.Map(document.getElementById('map'), {
              zoom: 15,
              center: test
            });
            var transitLayer = new google.maps.TransitLayer();
            transitLayer.setMap(map);
            var contentString = '住所：<%= @location.address %>';
            var infowindow = new google.maps.InfoWindow({
              content: contentString
            });
            var marker = new google.maps.Marker({
              position:test,
              map: map,
              title: contentString
            });
            marker.addListener('click', function() {
              infowindow.open(map, marker);
            });
          }
        </script>
        <script async defer
          src="https://maps.googleapis.com/maps/api/js?v=3.exp&key=<%= ENV['GOOGLE_MAP_API_KEY'] %>&callback=initMap">
        </script>
      </tr>
      <tr class="arrow_box">
        <th>スポット紹介</th>
        <td><%= @location.introduction %></td>
      </tr>
      <tr class="arrow_box">
        <th>口コミを見る</th>
        <td><%= link_to "レビューを見る", location_reviews_path(@location), class: "button light ml-3 mt-3" %></td>
      </tr>
    </thead>
  </table>
  <%= render 'reviews/form', review: @review, location: @location %>
</div>

app/views/reviews/_form.html.erb
<p class="is-size-4 mb-3">レビューを書く</p>
<% if review.errors.any? %>
  <div class="notification is-danger">
    <h2><%= review.errors.count %>件のエラーがあります。</h2>
    <ul>
      <% review.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>
<div class="rating-box mt-3">
  <%= form_with model: review, url: location_reviews_path(location), local: true do |f| %>
    <div class="main-rating">
      <div class="ratings mb-3">
        <span class="fa fa-star-o" id="star"></span>
        <span class="fa fa-star-o" id="star"></span>
        <span class="fa fa-star-o" id="star"></span>
        <span class="fa fa-star-o" id="star"></span>
        <span class="fa fa-star-o" id="star"></span>
      </div>
      <div class="ml-3 rating-value-display"><span id="rating-value-display">0</span>/5</div>
    </div>
    <%= f.hidden_field :location_id, value: location.id %>
    <%= f.hidden_field :score, id: "rating-value" %>
    <%= f.text_field :content, class: "textarea1" %>
    <%= f.submit "投稿", class: "button mt-3" %>
  <% end %>
</div>

<%= javascript_include_tag 'reviews.js' %>

app/views/reviews/index.html.erb
<section class="section mt-6">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-5">
        <div class="card mb-6">
          <header class="card-header">
            <p class="card-header-title">
              <%= @location.location_name %>
            </p>
          </header>
          <div class="card-content">
            <div class="content average-score">
              <div class="star-rating mb-2">
                <div class="star-rating-front" style="width: <%= @location.review_score_percentage %>%">★★★★★</div>
                <div class="star-rating-back">★★★★★</div>
              </div>
              <div class="average-score-display ml-3 pt-2">
                <%= @location.avg_score %>点（<%= @location.reviews.count %>件のレビュー）
              </div>
            </div>
          </div>
        </div>
        <table class="table is-fullwidth has-text-centered">
          <thead>
            <tr>
              <th>ユーザー</th><th>点数</th><th>内容</th>
            </tr>
          </thead>
          <tbody>
            <% @reviews.each do |review| %>
              <tr>
                <td><%= review.user.username %></td>
                <td><%= review.score %></td>
                <td><%= review.content %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</section>